version: "3.8"
services:
       app-demo:
           container_name: app-demo
           image: v1/app-demo
           restart: always
           build: .
           ports:
             - "3000:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'